saleor/dashboard/reports/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views
from . import charts
from . import pdfs
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
		url(r'^$', permission_required('reports.view_sales_reports', login_url='not_found')
			(views.sales_reports), name='sales_reports'),
		url(r'^sales/$', permission_required('reports.view_sales_reports', login_url='not_found')
			(views.sales_list), name='sales_list'),
		url(r'^detail/(?P<pk>[0-9]+)/$', permission_required('reports.view_sales_reports', login_url='not_found')
			(views.sales_detail), name='sale-detail'),
		url(r'^product_reports/$',  permission_required('reports.view_products_reports', login_url='not_found')
			(views.product_reports), name='products_reports'),
		url( r'^products_search/$', views.products_search, name = 'products_search' ),
		url( r'^products_paginate/$', views.products_paginate, name = 'products_paginate' ),
		url(r'^prd/$',  permission_required('reports.view_products_reports', login_url='not_found')
			(views.product_reorder), name='products_reorder'),
		url( r'^prs/$', views.products_reorder_search, name = 'products_reorder_search' ),
		url( r'^prp/$', views.products_reorder_paginate, name = 'products_reorder_paginate' ),

		url(r'^purchases_reports/$',  permission_required('reports.view_purchase_reports', login_url='not_found')
			(views.purchases_reports), name='purchases_reports'),
		url(r'^balancesheet_reports/$', permission_required('reports.view_balancesheet', login_url='not_found')
			(views.balancesheet_reports), name='balancesheet_reports'),
		url(r'^chart/$', views.get_dashboard_data, name='chart'), 
		url( r'^sales_search/$', views.sales_search, name = 'sales_search' ),
		url( r'^sales_paginate/$', views.sales_paginate, name = 'sales_paginate' ),
		url(r'^cpdf/(?P<image>.+)/$', pdfs.chart_pdf, name='chart_pdf'),
		url(r'^csv/(?P<image>.+)/$', pdfs.sales_export_csv, name='chart_csv'),

		url( r'^datechart/$',  permission_required('reports.view_sales_reports', login_url='not_found')
			(charts.sales_date_chart), name = 'sales_date_chart' ),
		url( r'^datechartimage/(?P<image>.+)/$', charts.sales_date_chart, name = 'sales_date_chart' ),
		url( r'^productchart/$',  permission_required('reports.view_products_reports', login_url='not_found')
			(charts.sales_product_chart), name = 'sales_product_chart' ),
		url( r'^ptd/$', charts.get_product_sale_details, name = 'get_product_sale_details' ),
		url( r'^category/$',  permission_required('reports.view_sales_reports', login_url='not_found')
			(charts.sales_category_chart), name = 'sales_category_chart' ),
		url( r'^catimage/(?P<image>.+)/$', charts.sales_category_chart, name = 'sales_category_chart' ),
		url( r'^catd/$', charts.get_category_sale_details, name = 'get_category_sale_details' ),
		url( r'^userchart/$',  permission_required('reports.view_sales_reports', login_url='not_found')
			(charts.sales_user_chart), name = 'sales_user_chart' ),
		url( r'^utd/$', charts.get_user_sale_details, name = 'get_user_sale_details' ),
		url( r'^tellerchart/$',  permission_required('reports.view_sales_reports', login_url='not_found')
			(charts.sales_terminal_chart), name = 'sales_terminal_chart' ),
		url( r'^ttd/$', charts.get_terminal_sale_details, name = 'get_terminal_sale_details' ),
		url( r'^weekfilter/$', charts.get_sales_by_week, name = 'get_sales_by_week' ),

]

if settings.DEBUG:
	# urlpatterns += [ url(r'^static/(?P<path>.*)$', serve)] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.search, name='search')
]

saleor/search/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.search, name='search')
]

saleor/urls.py
from rest_framework_jwt.views import obtain_jwt_token
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView
import notifications.urls

from .accounts.urls import urlpatterns as accounts_urls
from .api.cash.urls import urlpatterns as api_cash_urls
from .api.payment.urls import urlpatterns as api_payment_urls
from .api.product.urls import urlpatterns as api_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls

from .order.urls import urlpatterns as order_urls
from .payment.urls import urlpatterns as payment_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

from .api.product import views as api_views
from . import decorators


urlpatterns = [    
	url(r'^', include(core_urls)),    
	url(r'^account/', include(registration_urls)),
	url(r'^accounts/', include(accounts_urls, namespace='accounts')),
	url(r'^api/cash/', include(api_cash_urls, namespace='cash-api')),
	url(r'^api/products/', include(api_urls, namespace='product-api')),
	url(r'^api/payment/', include(api_payment_urls, namespace='payment-api')),
	url(r'^cart/', include(cart_urls, namespace='cart')),
	url(r'^checkout/', include(checkout_urls, namespace='checkout')),
	url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
	url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
	 url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
	url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
	url(r'^order/', include(order_urls, namespace='order')),
	url(r'^payment/$', include(payment_urls, namespace='payment')),
	url(r'^products/', include(product_urls, namespace='product')),
	url(r'^profile/', include(userprofile_urls, namespace='profile')),
	url(r'^search/', include(search_urls, namespace='search')),
	url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
	url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
		name='django.contrib.sitemaps.views.sitemap'),
	url(r'', include('payments.urls')),
	url('', include('social_django.urls', namespace='social')),
	#jwt post token code url
	url(r'^api/auth/token/', obtain_jwt_token),

]

if settings.DEBUG:
	# static files (images, css, javascript, etc.)
	urlpatterns += [
		url(r'^static/(?P<path>.*)$', serve)
	] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/reports/models.py
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404
from django.db import models
from django.conf import settings
from django.contrib.postgres.fields import HStoreField
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator, RegexValidator
from django.db.models import F, Max, Q
from django.contrib.auth.models import Group

saleor/dashboard/search/forms.py
from ...search.backends import get_search_backend
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):

    def search(self, queryset_map=None):
        backend = get_search_backend('dashboard')
        query = self.cleaned_data['q']
        results = backend.search(query, queryset_map=queryset_map)
        return results

saleor/dashboard/reports/views.py
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import get_object_or_404, redirect, render_to_response
from django.template.response import TemplateResponse
from django.utils.http import is_safe_url
from django.utils.translation import pgettext_lazy
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.hashers import make_password
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Count, Min, Sum, Avg, F, Q
from django.core import serializers
from django.template.defaultfilters import date
from django.core.paginator import Paginator, EmptyPage, InvalidPage, PageNotAnInteger
import datetime
from datetime import date, timedelta
from django.utils.dateformat import DateFormat
import logging

from ...core.utils import get_paginator_items
from ..views import staff_member_required
from ...userprofile.models import User
from ...sale.models import Sales, SoldItem, DrawerCash
from ...product.models import Product, ProductVariant
from ...purchase.models import PurchaseProduct
from ...decorators import permission_decorator, user_trail
from ...dashboard.views import get_low_stock_products

debug_logger = logging.getLogger('debug_logger')
info_logger = logging.getLogger('info_logger')
error_logger = logging.getLogger('error_logger')

@staff_member_required
@permission_decorator('reports.view_sales_reports')
def sales_list(request):
	try:
		try:
			last_sale = Sales.objects.latest('id')
			last_date_of_sales = DateFormat(last_sale.created).format('Y-m-d')
		except:
			last_date_of_sales = DateFormat(datetime.datetime.today()).format('Y-m-d')

		all_sales = Sales.objects.filter(created__contains=last_date_of_sales)
		total_sales_amount = all_sales.aggregate(Sum('total_net'))
		total_tax_amount = all_sales.aggregate(Sum('total_tax'))
		total_sales = []
		for sale in all_sales:
			quantity = SoldItem.objects.filter(sales=sale).aggregate(c=Count('sku'))
			setattr(sale, 'quantity', quantity['c'])
			total_sales.append(sale)

		page = request.GET.get('page', 1)
		paginator = Paginator(total_sales, 10)
		try:
			total_sales = paginator.page(page)
		except PageNotAnInteger:
			total_sales = paginator.page(1)
		except InvalidPage:
			total_sales = paginator.page(1)
		except EmptyPage:
			total_sales = paginator.page(paginator.num_pages)
		user_trail(request.user.name, 'accessed sales reports', 'view')
		info_logger.info('User: ' + str(request.user.name) + ' accessed the view sales report page')
		if request.GET.get('initial'):
			return HttpResponse(paginator.num_pages)
		else:
			return TemplateResponse(request, 'dashboard/reports/sales/sales_list.html',{'sales': total_sales, "total_sales_amount":total_sales_amount, "total_tax_amount":total_tax_amount,"date":last_date_of_sales})
	except ObjectDoesNotExist as e:
		error_logger.error(e)

@staff_member_required
@permission_decorator('reports.view_sales_reports')
def sales_detail(request, pk=None):
	try:
		sale = Sales.objects.get(pk=pk)
		items = SoldItem.objects.filter(sales=sale)
		return TemplateResponse(request, 'dashboard/reports/sales/details.html',{'items': items, "sale":sale})
	except ObjectDoesNotExist as e:
		error_logger.error(e)

@staff_member_required
@permission_decorator('reports.view_sales_reports')
def sales_reports(request):
	try:
		today = datetime.date.today()
		items = SoldItem.objects.all().order_by('-id')
		ts = Sales.objects.filter(created__icontains=today)
		tsum = ts.aggregate(Sum('total_net'))
		total_sales = Sales.objects.aggregate(Sum('total_net'))
		total_tax = Sales.objects.aggregate(Sum('total_tax'))
		page = request.GET.get('page', 1)
		paginator = Paginator(items, 10)
		try:
			items = paginator.page(page)
		except PageNotAnInteger:
			items = paginator.page(1)
		except InvalidPage:
			items = paginator.page(1)
		except EmptyPage:
			items = paginator.page(paginator.num_pages)
		user_trail(request.user.name, 'accessed sales reports','view')
		info_logger.info('User: '+str(request.user.name)+' accessed the view sales report page')
		if request.GET.get('initial'):
			return HttpResponse(paginator.num_pages)
		else:
			return TemplateResponse(request, 'dashboard/reports/sales/sales.html', {'items':items, 'total_sales':total_sales,'total_tax':total_tax, 'ts':ts, 'tsum':tsum})
	except TypeError as e:
		error_logger.error(e)
		return HttpResponse('error accessing sales reports')

@staff_member_required
def sales_paginate(request):
	page = int(request.GET.get('page'))
	list_sz = request.GET.get('size')
	date = request.GET.get('date')
	action = request.GET.get('action')
	p2_sz = request.GET.get('psize')
	select_sz = request.GET.get('select_size')
	gid = request.GET.get('gid')
	sales = Sales.objects.all().order_by('-id')
	today_formart = DateFormat(datetime.date.today())
	today = today_formart.format('Y-m-d')
	ts = Sales.objects.filter(created__icontains=today)
	tsum = ts.aggregate(Sum('total_net'))
	total_sales = Sales.objects.aggregate(Sum('total_net'))
	total_tax = Sales.objects.aggregate(Sum('total_tax'))

	if request.GET.get('sth'):
		all_sales = Sales.objects.filter(created__icontains=date).order_by('-id')
		sales = []
		for sale in all_sales:
			quantity = SoldItem.objects.filter(sales=sale).aggregate(c=Count('sku'))
			setattr(sale, 'quantity', quantity['c'])
			sales.append(sale)
		if date:
			try:
				all_salesd = Sales.objects.filter(created__icontains=date).order_by('-id')
				that_date_sum = Sales.objects.filter(created__contains=date).aggregate(Sum('total_net'))
				sales = []
				for sale in all_salesd:
					quantity = SoldItem.objects.filter(sales=sale).aggregate(c=Count('sku'))
					setattr(sale, 'quantity', quantity['c'])
					sales.append(sale)

				if p2_sz and gid:
					paginator = Paginator(sales, int(p2_sz))
					sales = paginator.page(page)
					return TemplateResponse(request,'dashboard/reports/sales/paginate.html',{'sales':sales, 'gid':date})

				paginator = Paginator(sales, 10)
				sales = paginator.page(page)
				return TemplateResponse(request,'dashboard/reports/sales/p2.html',
					{'sales':sales, 'pn':paginator.num_pages,'sz':10,'gid':date,
					'total_sales':total_sales,'total_tax':total_tax,'tsum':tsum, 
					'that_date_sum':that_date_sum, 'date':date, 'today':today})

			except ObjectDoesNotExist as e:
				return TemplateResponse(request, 'dashboard/reports/sales/p2.html',{'date': date})
		if action:
			try:
				all_sales2 = Sales.objects.filter(created__icontains=date).order_by('-id')
				sales = []
				for sale in all_sales2:
					quantity = SoldItem.objects.filter(sales=sale).aggregate(c=Count('sku'))
					setattr(sale, 'quantity', quantity['c'])
					sales.append(sale)
				if p2_sz and gid:
					paginator = Paginator(sales, int(p2_sz))
					sales = paginator.page(page)
					return TemplateResponse(request,'dashboard/reports/sales/paginate.html',{'sales':sales, 'gid':action})

				paginator = Paginator(sales, 10)
				sales = paginator.page(page)
				return TemplateResponse(request,'dashboard/reports/sales/p2.html',
					{'sales':sales, 'pn':paginator.num_pages,'sz':10,'gid':action,
					'total_sales':total_sales,'total_tax':total_tax, 'tsum':tsum})

			except ObjectDoesNotExist as e:
				return TemplateResponse(request, 'dashboard/reports/sales/p2.html', {'date': date})
	else:
		try:
			last_sale = Sales.objects.latest('id')
			last_date_of_sales = DateFormat(last_sale.created).format('Y-m-d')
			all_sales = Sales.objects.filter(created__contains=last_date_of_sales)
			total_sales_amount = all_sales.aggregate(Sum('total_net'))
			total_tax_amount = all_sales.aggregate(Sum('total_tax'))
			sales = []
			for sale in all_sales:
				quantity = SoldItem.objects.filter(sales=sale).aggregate(c=Count('sku'))
				setattr(sale, 'quantity', quantity['c'])
				sales.append(sale)

			if list_sz:
				paginator = Paginator(sales, int(list_sz))
				sales = paginator.page(page)
				return TemplateResponse(request,'dashboard/reports/sales/p2.html',{'sales':sales, 'pn':paginator.num_pages,'sz':list_sz, 'gid':0, 'total_sales':total_sales,'total_tax':total_tax, 'tsum':tsum})
			else:
				paginator = Paginator(sales, 10)
			if p2_sz:
				paginator = Paginator(sales, int(p2_sz))
				sales = paginator.page(page)
				return TemplateResponse(request,'dashboard/reports/sales/paginate.html',{'sales':sales})

			if date:
				try:
					all_sales2 = Sales.objects.filter(created__icontains=date).order_by('-id')
					that_date = Sales.objects.filter(created__icontains=date)
					that_date_sum = that_date.aggregate(Sum('total_net'))
					sales = []
					for sale in all_sales2:
						quantity = SoldItem.objects.filter(sales=sale).aggregate(c=Count('sku'))
						setattr(sale, 'quantity', quantity['c'])
						sales.append(sale)
					if p2_sz:
						paginator = Paginator(sales, int(p2_sz))
						sales = paginator.page(page)
						return TemplateResponse(request,'dashboard/reports/sales/paginate.html',{'sales':sales, 'gid':date})

					paginator = Paginator(sales, 10)
					sales = paginator.page(page)
					return TemplateResponse(request,'dashboard/reports/sales/p2.html',
						{'sales':sales, 'pn':paginator.num_pages,'sz':10,'gid':date,
						'total_sales':total_sales,'total_tax':total_tax, 'tsum':tsum,
						'that_date_sum':that_date_sum, 'date':date, 'today':today})

				except ObjectDoesNotExist as e:
					return TemplateResponse(request, 'dashboard/reports/sales/p2.html', {'date': date})

			try:
				sales = paginator.page(page)
			except PageNotAnInteger:
				sales = paginator.page(1)
			except InvalidPage:
				sales = paginator.page(1)
			except EmptyPage:
				sales = paginator.page(paginator.num_pages)

templates/dashboard/reports/sales/sales.html
{% extends "dashboard/base.html" %}
{% load staticfiles i18n %}
{% load i18n %}
{% load prices_i18n %}

{% block title %}
  Sales Report
{% endblock %}
{% block breadcrumbs %}
     <li><a href="{% url 'dashboard:sales_reports' %}">Reports</a></li>
     <li class="active"><a href="{% url 'dashboard:sales_reports' %}">Sales</a></li>
 {% endblock %}

{% block menu_report_class %}active{% endblock %}
 {% block custom_css %}
   <style type="text/css">
    label.error{
      color: #FF5722;
    }
  </style>
 {% endblock %}

{% block content %}
<div class="row animated fadeIn">
    <div class="col-md-12">
      <div class="panel panel-flat">
      <div class="panel-heading">
        <h6 class="panel-title">Sales Reports</h6>
        <div class="heading-elements">
          <ul class="icons-list">
            <li><a data-action="collapse"></a></li>
            <li><a data-action="reload"></a></li>
            <li><a data-action="close"></a></li>
          </ul>
        </div>
      <a class="heading-elements-toggle"><i class="icon-more"></i></a></div>
        <div class="panel-body">
            <div class="col-md-6">
             <label>Search Sales</label>
              <div class="form-group form-group-material has-feedback">
                <input class="form-control search_user" placeholder="Search details" type="text">
                <div class="form-control-feedback">
                  <i class="icon-search4 text-size-base"></i>
                </div>
              </div>
            </div>
            <div class="col-md-2">
              <label>display list size</label>
              <div class="form-group">
                 <select class="bootstrap-select list-sz" style="display: none;" data-width="100%" tabindex="-98">
                    <option value="0" selected>No:</option>
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                  </select>
              </div>
            </div>
            <div class="col-md-2">
              <label>pick a date</label>
              <div class="form-group">
                <div class="input-group">
                  <input class="form-control daterange-single" type="text">
                  <span class="input-group-addon"><i class="icon-calendar22"></i></span>
                </div>
              </div>
            </div>
            <div class="col-md-2">
             <label>Export</label>
              <div class="form-group">
                 <select class="bootstrap-select export-sz" style="display: none;" data-width="100%" tabindex="-98">
                    <option value="none" data-icon="fa fa-dot-circle-o">Option</option>
                    <option value="pdf" data-icon="fa-file-pdf-o">export pdf</option>
                    <option value="excel" data-icon="fa-file-excel-o">export excel</option>
                  </select>
              </div>
            </div>
      </div>
   </div>
   </div>

<div class="col-md-12">
   <div id="pagination-div">
    <div class="panel panel-flat">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-12">
            <div class="table-responsives">     
                <table class="table table-bordered datatable-header-footer">
                  <caption style="margin-bottom: 10px;">
                   </caption> 
                      <thead style="border-top:1px solid #ddd;">
                        <tr>
                          <th>Transaction Date</th>
                          <th>Receipt No</th>
                          <th>Client Name</th>
                          <th>Item Name</th>
                          <th>Unit Cost</th>
                          <th>Quantity</th>
                          <th>Total Sales</th>
                        </tr>
                      </thead>
                      <tbody id="tb">
                        {% if items %}
                        {% for item in items %}
                          <tr>
                            <td>{{item.sales.created|date:"d-m-Y H:i a"}}</td>
                            <td>{{item.sales.invoice_number }}</td>
                            <td>{% if item.sales.user.email %}{{item.sales.user.email}}{% else %}{{item.sales.user.name}}{% endif %}</td>
                            <td>{{item.product_name}}</td>
                            <td>{{item.unit_cost}}</td>
                            <td>{{item.quantity}}</td>
                            <td>{{item.total_cost}}</td>
                          </tr>
                        {% endfor %}
                        {% else %}
                         <tr><td colspan="6"><h2 class="text-center">no sales available</h2></td></tr>
                        {% endif %}
                        </tbody>

                 </table>
              </div>
              <div class="my-paginate">
                <div class="text-center bootpag-callback" style="padding:20px;">
                  <ul class="pagination bootpag pagination-flat pagination-sm"></ul>
                  <div class="pull-right pages-nav">Page 1</div>
                </div>
                <input type="hidden" id="page_size" val="">
              </div>
             </div>
            </div>
            <div class="row">
              <div class="col-md-10 col-md-offset-1">
                 <p class="text-center" style="margin: 20px 0px;">
                   Todays Sales: Kshs 
                    {% if tsum.total_net__sum %}
                       {{tsum.total_net__sum}} 
                    {% else %}
                       0.00<br />
                    {% endif %}<br />
                   Total Sales: Kshs {{total_sales.total_net__sum}}<br />
                   Total Tax: Kshs {{ total_tax.total_tax__sum}}
                 </p>
                  <p class="text-center"> Thank you for partnering with us.<br />
                  <span>Report pullled by {{request.user.name}}</span></p>
                  <input type="hidden" class="setValue">
                  <input type="hidden" class="setName">
                  <!--<button class="btn btn-primary ck">Click</button> -->
                  
              </div>
             </div>
            </div>
<!--       <div class="panel-footer">
      <button class="btn btn-primary disabled">checki this</button>
      </div> -->
    </div>
   </div><!--pagination div-->
  </div>
</div>


{% endblock%}
{% block custom_js %}
  <script type="text/javascript" src="{% static 'backend/js/plugins/forms/selects/bootstrap_multiselect.js' %}"></script> 
  <script type="text/javascript" src="{% static 'backend/js/pages/form_multiselect.js' %}"></script>
<script type="text/javascript" src="{% static 'backend/js/plugins/forms/selects/bootstrap_select.min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){

    var pagination_totalsize;
    var status;
    //**@ get
    $.ajax({ url: "{% url 'dashboard:sales_reports' %}",type: 'GET',data: {initial:'initial'},
        async:false,success: function(data){
         pagination_totalsize = data;
    }}); 

     $('.bootpag-callback').bootpag({
        total: parseInt(pagination_totalsize),
        maxVisible: 3,
        leaps: false
        }).on("page", function(event, num){
            $(".pages-nav").html("Page " + num +" of "+pagination_totalsize);
            $.get("{% url 'dashboard:sales_paginate' %}",{page:parseInt(num)},function(data){
               $('#tb').html(data);
            });
    }).children('.pagination').addClass('pagination-flat pagination-sm'); 

    $('.daterange-single').daterangepicker({ 
        singleDatePicker: true,
        locale:{format: 'YYYY-MM-DD'},
        showDropdowns:true
    }).on('change',function(){
      var date = $(this).val();
        $.ajax({ url: "{% url 'dashboard:sales_paginate' %}",type: 'GET',data: {page:1, date:date }, async:false,success: function(data){
              $('#pagination-div').html(data);
        }});
    });

   $('.export-sz').selectpicker({
          iconBase: 'fa',
          tickIcon: 'fa-dot-circle-o',
          pdfIcon:'fa-file-pdf-o',
          excelIcon:'fa-file-excel-o'
    }).on('change',function(){
         $('.setValue').val($(this).val());
         $('.setName').val('export');
         // $('.set').value = $(this).val();
    });
    $('.ck').click(function(){
      var name = $('.setName').val();
      var vl = $('.setValue').val();
        if( !name || !vl || vl == 'none'){
           alert('nothing');
        }else{
         alert(name +' and '+ vl);
        }
    });
    //**@ display size select
    $('.list-sz').selectpicker().on('change', function(){
        var ts = $(this).val();
        $.ajax({ url: "{% url 'dashboard:sales_paginate' %}",type: 'GET',data: {page:1, size:ts}, async:false,success: function(data){
              $('#pagination-div').html(data);
        }});
     });



      var delay = (function(){
    var timer = 0;
    return function(callback, ms){
        clearTimeout (timer);
        timer = setTimeout(callback, ms);
      };
    })();

    $('.search_user').keyup(function() {
      var search_text = $(this).val();
      delay(function(){ 
         var url = "{% url 'dashboard:sales_search' %}";
         $.ajax({ url:url, type: 'GET',data: {page:1, q:search_text},success: function(data){
                $('#pagination-div').html(data);
         }});
      }, 500 );

    });


});

</script>
{% endblock %}