saleor/api/product/urls.py
from django.conf.urls import url

from .views import (
    CreateStockAPIView,
    CustomerListAPIView,
    CustomerDetailAPIView,
    ProductListAPIView,
    ProductStockListAPIView,
    SearchSkuListAPIView,
    SalesListAPIView,
    SalesCreateAPIView,
    SalesDetailAPIView,
    SalesDeleteAPIView,
    )


urlpatterns = [
    url(r'^$', ProductListAPIView.as_view(), name='product-list'),
    url(r'^stock$', ProductStockListAPIView.as_view(), name='productstock-list'),
    url(r'^stock/(?P<stock_pk>[0-9]+)$', CreateStockAPIView.as_view(), name='create-stock'),
    url(r'^search-sku/$', SearchSkuListAPIView.as_view(), name='search-sku'),
    url(r'^customer/list/$', CustomerListAPIView.as_view(), name='customer-list'),
    url(r'^customer/list/$', CustomerListAPIView.as_view(), name='customer-list'),
    url(r'^customer-details/(?P<pk>[0-9]+)/$', CustomerDetailAPIView.as_view(), name='costomer-detail'),
    url(r'^list-orders/$', SalesListAPIView.as_view(), name='list-orders'),
    url(r'^create-order/$', SalesCreateAPIView.as_view(), name='create-order'),
    url(r'^sales-details/(?P<pk>[0-9]+)/$', SalesDetailAPIView.as_view(), name='sales-details'),
    url(r'^sales-delete/(?P<pk>[0-9]+)/$', SalesDeleteAPIView.as_view(), name='sales-delete'),

]

saleor/dashboard/product/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from . import api
from . import views, products


urlpatterns = [
    # url(r'^$',permission_required('product.view_product', login_url='not_found')
    # (views.product_list), name='product-list'),

    url(r'^$',permission_required('product.view_product', login_url='not_found')
    (products.view), name='product-list'),
    url(r'^list-paginate/$', products.paginate, name='product-list-paginate'),
    url(r'^list/search/$', products.search, name='product-list-search'),
    url(r'^(?P<pk>[0-9]+)/update/$', permission_required('product.change_product', login_url='not_found')
        (views.product_edit), name='product-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', permission_required('product.delete_product', login_url='not_found')
        (views.product_delete), name='product-delete'),
    url(r'^add/(?P<class_pk>[0-9]+)/$', permission_required('product.add_product', login_url='not_found')
        (views.product_create), name='product-add'),
    url(r'^add/$', permission_required('product.add_product', login_url='not_found')
    (views.product_create), name='product-add'),
    url(r'^fetch_variants/$', permission_required('product.view_product', login_url='not_found')
        (views.fetch_variants), name='fetch-variants'),
    # tax routes
    url(r'^tax/$', permission_required('product.view_producttax', login_url='not_found')
        (views.tax_list), name='tax-list'),
    url(r'^tax/add$', permission_required('product.add_producttax', login_url='not_found')
        (views.tax_add), name='tax-add'),
    url(r'^tax/add/ajax$',
        views.tax_add_ajax, name='tax-add-ajax'),    
    url(r'^tax/delete/(?P<pk>[0-9]+)/$', permission_required('product.delete_producttax', login_url='not_found')
        (views.tax_delete), name='tax-delete'),
    url(r'^tax/edit(?P<pk>[0-9]+)/$', permission_required('product.change_producttax', login_url='not_found')
        (views.tax_edit), name='tax-update'),
    # end tax
    # purchase routes
    url(r'^purchase/$', permission_required('product.view_stock', login_url='not_found')
        (views.stocks), name='purchase-list'),
    # end purchase routes
    # search routes
    url(r'^search_ajax/$',
        views.search_product, name='search-product'),
    url(r'^search_sku/$',
        views.search_sku, name='search-sku'),
    url(r'^search_productclass/$',
        views.search_productclass, name='search-type'),
    # pagination
    url(r'^stocks/$', permission_required('product.view_stock', login_url='not_found')
        (views.stocks), name='stocks'),
    url(r'^stock_paginate/$', views.stock_paginate, name='stock_paginate'),
    url(r'^stock_pages/$', permission_required('product.view_stock', login_url='not_found')
    (views.stock_pages), name='stock_pages'),
    url( r'^stock_search/$', views.stock_search, name = 'stock_search' ),
    url(r'^stock_filter/$',
        views.stock_filter, name='stock_filter'),
     
     url(r'^product_pages/$',
        views.stock_pages, name='product_pages'),
     url(r'^product_filter/$',
        views.product_filter, name='product_filter'),
    # end search routes
    # url(r'^classes/$', permission_required('product.view_productclass', login_url='not_found')
    #     (views.product_class_list), name='product-class-list'),
    url(r'^classes/$', permission_required('product.view_productclass', login_url='not_found')
            (views.class_list_view), name='product-class-list'),
    url(r'^classes/paginate/$', permission_required('product.view_productclass', login_url='not_found')
            (views.paginate_class_list), name='paginate-class-list'),
    url(r'^classes/search/$', permission_required('product.view_productclass', login_url='not_found')
            (views.search_class_list), name='search-class-list'),
    url(r'^classes/add/$', permission_required('product.add_productclass', login_url='not_found')
        (views.product_class_create), name='product-class-add'),
    url(r'^classes/refresh/$',
        views.refresh_producttype, name='refresh_producttype'),    
    
    url(r'^classes/add/new_window/(\d+)/$', permission_required('product.add_productclass', login_url='not_found')
        (views.product_class_create), name='product-class-add-new'),
    
    url(r'^classes/(?P<pk>[0-9]+)/update/$', permission_required('product.change_productclass', login_url='not_found')
        (views.product_class_edit), name='product-class-update'),
    url(r'^classes/(?P<pk>[0-9]+)/delete/$', permission_required('product.delete_productclass', login_url='not_found')
        (views.product_class_delete), name='product-class-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$', permission_required('product.change_productvariants', login_url='not_found')
        (views.variant_edit), name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/add/$', permission_required('product.add_productvariants', login_url='not_found')
        (views.variant_edit), name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$', permission_required('product.delete_productvariants', login_url='not_found')
        (views.variant_delete), name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/bulk_delete/', permission_required('product.delete_productvariants', login_url='not_found')
        (views.variants_bulk_delete), name='variant-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/$', permission_required('product.change_stock', login_url='not_found')
        (views.stock_edit), name='product-stock-update'),
    url(r'^stock/(?P<stock_pk>[0-9]+)/history$', permission_required('product.view_stock', login_url='not_found')
        (views.stock_history), name='stock-history'),
    url(r'^(?P<product_pk>[0-9]+)/stock/add/$', permission_required('product.add_stock', login_url='not_found')
        (views.stock_edit), name='product-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/delete/$', permission_required('product.delete_stock', login_url='not_found')
        (views.stock_delete), name='product-stock-delete'),
    url(r'^(?P<product_pk>[0-9]+)/stock/bulk_delete/', permission_required('product.delete_stock', login_url='not_found')
        (views.stock_bulk_delete), name='stock-bulk-delete'),
    url(r'^add_stock_ajax/$',
        views.add_stock_ajax,name='add_stock_ajax'),
    url(r'^re_order/$',
        views.re_order,name='re_order'),
    url(r'^re_order/form/(?P<pk>[0-9]+)$',
        views.re_order_form,name='re_order_form'),
    url(r'^re_order/form/item/(?P<pk>[0-9]+)$',
        views.add_reorder_stock,name='reorder_stock'),
    url(r'^re_order/request/$',
        views.request_order,name='request_order'),  
           

    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$', permission_required('product.change_productimage', login_url='not_found')
        (views.product_image_edit), name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$', permission_required('product.add_productimage', login_url='not_found')
        (views.product_image_edit), name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$', permission_required('product.delete_productimage', login_url='not_found')
        (views.product_image_delete), name='product-image-delete'),
    url('^(?P<product_pk>[0-9]+)/images/reorder/$', permission_required('product.change_productimage', login_url='not_found')
        (api.reorder_product_images), name='product-images-reorder'),
    url('^(?P<product_pk>[0-9]+)/images/upload/$', permission_required('product.add_productimage', login_url='not_found')
        (api.upload_image), name='product-images-upload'),

    # url(r'attributes/$', permission_required('product.view_productattribute', login_url='not_found')
    #     (views.attribute_list), name='product-attributes'),
    url(r'attributes/$', permission_required('product.view_productattribute', login_url='not_found')
        (views.view_attr), name='product-attributes'),
    url(r'attributes/paginate/$', permission_required('product.view_productattribute', login_url='not_found')
        (views.paginate_attr), name='attr_paginate'),
    url(r'attributes/search$',
        views.search_attribute, name='search-attribute'),
    
    url(r'attributes/(?P<pk>[0-9]+)/$', permission_required('product.change_productattribute', login_url='not_found')
        (views.attribute_edit), name='product-attribute-update'),
    url(r'attributes/add/$', permission_required('product.add_productattribute', login_url='not_found')
        (views.attribute_edit), name='product-attribute-add'),
    url(r'attributes/add/modal/$', permission_required('product.add_productattribute', login_url='not_found')
    (views.attribute_add_modal), name='product-attribute-add-modal'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$', permission_required('product.delete_productattribute', login_url='not_found')
        (views.attribute_delete), name='product-attribute-delete'),

    url(r'attributes/ajax_add/$',
        views.attribute_add, name='product-attr-add'),
    url(r'attributes/ajax_add/(\d+)/$',
        views.attribute_add, name='product-attr-add-value'),
    

    url(r'stocklocations/$', permission_required('product.view_stocklocation', login_url='not_found')
        (views.stock_location_list), name='product-stock-location-list'),
    url(r'stocklocations/add/$', permission_required('product.add_stocklocation', login_url='not_found')
        (views.stock_location_edit), name='product-stock-location-add'),
    url(r'stocklocations/(?P<location_pk>[0-9]+)/$', permission_required('product.change_stocklocation', login_url='not_found')
    (views.stock_location_edit), name='product-stock-location-edit'),

saleor/product/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
    url(r'^category/(?P<path>[a-z0-9-_/]+?)-(?P<category_id>[0-9]+)/$',
        views.category_index, name='category'),
    url(r'(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/add/$',
        views.product_add_to_cart, name="add-to-cart"),
]

saleor/urls.py
from rest_framework_jwt.views import obtain_jwt_token
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView
import notifications.urls

from .accounts.urls import urlpatterns as accounts_urls
from .api.cash.urls import urlpatterns as api_cash_urls
from .api.payment.urls import urlpatterns as api_payment_urls
from .api.product.urls import urlpatterns as api_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls

from .order.urls import urlpatterns as order_urls
from .payment.urls import urlpatterns as payment_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

from .api.product import views as api_views
from . import decorators


urlpatterns = [    
	url(r'^', include(core_urls)),    
	url(r'^account/', include(registration_urls)),
	url(r'^accounts/', include(accounts_urls, namespace='accounts')),
	url(r'^api/cash/', include(api_cash_urls, namespace='cash-api')),
	url(r'^api/products/', include(api_urls, namespace='product-api')),
	url(r'^api/payment/', include(api_payment_urls, namespace='payment-api')),
	url(r'^cart/', include(cart_urls, namespace='cart')),
	url(r'^checkout/', include(checkout_urls, namespace='checkout')),
	url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
	url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
	 url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
	url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
	url(r'^order/', include(order_urls, namespace='order')),
	url(r'^payment/$', include(payment_urls, namespace='payment')),
	url(r'^products/', include(product_urls, namespace='product')),
	url(r'^profile/', include(userprofile_urls, namespace='profile')),
	url(r'^search/', include(search_urls, namespace='search')),
	url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
	url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
		name='django.contrib.sitemaps.views.sitemap'),
	url(r'', include('payments.urls')),
	url('', include('social_django.urls', namespace='social')),
	#jwt post token code url
	url(r'^api/auth/token/', obtain_jwt_token),

]

if settings.DEBUG:
	# static files (images, css, javascript, etc.)
	urlpatterns += [
		url(r'^static/(?P<path>.*)$', serve)
	] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/product/forms.py
from __future__ import unicode_literals

import json

from django import forms
from django.utils.encoding import smart_text
from django.utils.translation import pgettext_lazy
from django_prices.templatetags.prices_i18n import gross

from ..cart.forms import AddToCartForm


class VariantChoiceField(forms.ModelChoiceField):
    discounts = None

    def label_from_instance(self, obj):
        variant_label = smart_text(obj)
        label = pgettext_lazy(
            'Variant choice field label',
            '%(variant_label)s - %(price)s') % {
                'variant_label': variant_label,
                'price': gross(obj.get_price(discounts=self.discounts))}
        return label


class ProductForm(AddToCartForm):
    variant = VariantChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        variant_field = self.fields['variant']
        variant_field.queryset = self.product.variants
        variant_field.discounts = self.cart.discounts
        variant_field.empty_label = None
        images_map = {variant.pk: [vi.image.image.url
                                   for vi in variant.variant_images.all()]
                      for variant in self.product.variants.all()}
        variant_field.widget.attrs['data-images'] = json.dumps(images_map)

    def get_variant(self, cleaned_data):
        return cleaned_data.get('variant')

templates/dashboard/product/attributes/_edit_values.html
<div class="modal-body">
    <div class="row">
    <form method="post" enctype="multipart/form-data">    
         <div class="col-md-12">
            <div class="form-group">
             <label>Name</label>
             {% if product_type %}
              <input type="text" id="attr_name" class="form-control" disabled="disabled" value="{{product_type}}" name="slug">
             <input type="hidden" class="product_type" value="{{product_type.pk}}" name="product_type">
             {% else %}
              <input type="text" id="attr_name" class="form-control" value="" name="slug">
             <input type="hidden" class="product_type" value="" name="product_type">
             {% endif %}

            
             <span class="help-block">Attribute name e.g Brand</span>
            </div>
          </div>

          <div class="col-md-12">
              <div class="row">
           {% for attr in attributes %}
           <div class="col-md-12">
            <label>Name: {{ attr }}</label><br>
            </div>
            <div class="col-md-6">
             <div class="input-group">
              <input type="text" placeholder="New value" name="choice" class="form-control" id="choice{{attr.pk}}">
              <span class="input-group-btn">
                <button class="btn btn-xs bg-primary legitRipple" type="button" id="cbtn{{attr.pk}}">add</button>
              </span>
            </div> 
            </div>

            <div class="col-md-6 add_value{{attr.pk}}">
                 <div class="tokenfield form-control">
                    <input class="form-control token-field" value="California,Washington" placeholder="- Bootstrap Tokenfield" style="position: absolute; left: -10000px;" tabindex="-1" type="text">
                    <input style="position: absolute; left: -10000px;" tabindex="-1" type="text">
                  {% for v in attr.values.all %}
                    <div class="token bg-success">
                        <span class="token-label" style="max-width: 457px;padding: 8px 20px 8px 16px;">{{ v }}</span>
                        <!--<a href="#" class="close" tabindex="-1">×</a>-->
                    </div>
                  {% endfor %}
                </div>

               </div>
               <script type="text/javascript">
              $('#cbtn{{attr.pk}}').on('click',function(){
                var value = $('#choice{{attr.pk}}').val();
                if(!value){ 
                notify('add a valid attribute name');
                return false; 
              }
              var url ='{% url "dashboard:product-attr-add-value" attr.pk %}';
              var csrf_token = jQuery("[name=csrfmiddlewaretoken]").val();          
              var posting = $.post( url, {       
                value:value,                
                csrfmiddlewaretoken:csrf_token,
              });    
              posting.done(function(data) {       
                  $('.add_value{{attr.pk}}').empty().append( data );
                  $('#choice{{attr.pk}}').val('');
                  //$('#add_value').addClass('hidden');
                           
                notify('New category added successfully','bg-success');
                refreshAttributes()
                
              });

              posting.fail(function(){
                notify('Oops! Try another value.','bg-warning');
              });
                
              });
            </script>
           {% endfor %}
          </div>
          </div>
          
      <!-- action buttons -->
         <div class="text-right">
     </div>
      </form>
    </div>
  </div>
<div class="modal-footer text-center">
    <button type="button" id='refresh_content' onclick="refreshAttributes()" class="btn btn-block btn-lg btn-default" data-dismiss="modal">Close</button>
</div>

templates/dashboard/product/attributes/add_value.html
{% if choices %}
	<div class="form-group">
	{% for choice in choices %}
		<span class="label label-primary" style='margin-top:8px;'>
		<i class="icon-"></i>
		{{ choice.name }}
		</span>
	{% endfor %}
   </div>
{% endif %}
<div class="form-group hidden" id='add_value'>
  	<label>Value</label>
	<input type="text" id='value' class="form-control" name="value">
 	<span class="help-block">Attribute value e.g Sony
 	</span>
</div>

templates/dashboard/product/attributes/confirm_delete.html
{% extends "dashboard/base.html" %}
{% load i18n %}

{% block title %}
  {% trans "Delete attribute" context "Delete attribute page title" %} - {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
  <ul class="breadcrumbs breadcrumbs--with-menu">
    <li>
      <a href="{% url 'dashboard:product-attributes' %}" class="breadcrumbs--ellipsed-item">
        {% trans "Attributes" context "Dashboard attributes list" %}
      </a>
    </li>
    <li>
      <span class="breadcrumbs--ellipsed-item">
        {% trans "Delete attribute" context "Delete attribute breadcrumbs" %}
      </span>
    </li>
  </ul>
{% endblock %}

{% block content %}
  <p>
    {% trans "Are you sure you want to delete the following attribute?" context "Delete attribute text" %}
  </p>
  <form method="post" novalidate>
    {% csrf_token %}
    <div class="row">
      <ul class="collection">
        <li class="collection-item">
          {{ attribute }}
        </li>
      </ul>
    </div>

    <div class="row">
      <div class="col m6 l4 offset-m3 offset-l4 right-align">
        <a href="{% url 'dashboard:product-attributes' %}" class="btn-flat">
          {% trans "Cancel" context "Dashboard cancel action" %}
        </a>
        <button type="submit" class="btn materialize-red">
          {% trans "Delete" context "Dashboard delete action" %}
        </button>
      </div>
    </div>
  </form>
{% endblock %}

templates/dashboard/product/attributes/list.html
{% extends "dashboard/base.html" %}
{% load i18n %}
{% load materializecss %}
{% load staticfiles %}

{% block title %}
  {% trans "Attributes" context "Dashboard attributes list" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-attributes{% endblock %}

{% block menu_attributes_class %}active{% endblock %}


{% block breadcrumbs %}
  
    <li class="active">
      {% trans "Attributes" context "Dashboard attributes list" %}
    </li>

{% endblock %}

{% block menu_catalogue_class %} active{% endblock %}

{% block content %}
  {% if attributes %}
  <div class="row">
      <!-- search -->
      <div class="col-md-12">
      <div class="panel panel-flat">
        <div class="panel-heading">      
          <div class="heading-elements">
            <ul class="icons-list">              
              <li><a data-action="collapse"></a></li>       
              <li><a data-action="close"></a></li>
            </ul>
          </div>
        </div>
        <div class="panel-body">
            <div class="col-md-6">
    {% url "dashboard:search-attribute" as url %}
            
    {% include "dashboard/includes/_search_filter.html" with url=url  %}
            </div>
            <!--  -->
            <div class="col-md-2">
              <div class="form-group">
                {% if perms.userprofile.add_user %}
                   <a href="{% url 'dashboard:product-attribute-add' %}" class="btn-block btn-primary btn-lg text-center">ADD ATTRIBUTE</a>
                {% endif %}
              </div>
            </div> 
        </div>
      </div>
   </div>
  <!-- end search -->
  </div>
  <div class="panel">
  <table class="table table-striped table-hover fixed_headers">          
  <!-- Header and footer fixed -->
    <thead>         
      <tr class="bg-primary">   
        <th>#</th>   
        <th>Name</th>    
        <th>Value</th>                 
        <th class="text-center">Actions</th>
      </tr>   
    </thead>                     
    <tbody id='content-search'>
    {% for pk, name, values in attributes %}
      <tr>
        <td>{{ pk }}</td>
        <!-- names -->
        <td>{{ name }}</td>
        <!-- values -->
        <td>
        {% if values %}
          {% for value in values %}
              {{ value }}
              {% if not forloop.last %}, {% endif %}
          {% endfor %}
        {% else %}
            None
        {% endif %}
        </td>
          <td class="text-center">
                  <!-- Single button -->
                <div class="btn-group">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Action <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu edit-dropdown">
                 {% if perms.product.change_product %}
                    <li><a href="{% url 'dashboard:product-attribute-update' pk=pk %}"><i class="icon-pencil7"></i> EDIT</a></li>
                 {% endif %}
                 {% if perms.product.delete_product %}
                      <li>
                         <a href="#modal_instance" data-title='Remove attribute {{ name }}' data-href="{% url 'dashboard:product-attribute-delete' pk=pk %}" class="modal-trigger-ajax"><i class="icon-trash position-left"></i>
                           REMOVE
                          </a>
                       </li>
                 {% endif %}
                  </ul>
                </div>

              </td>
      </tr>
    {% endfor %}
    </tbody>
    </table>
    </div>
    

  {% else %}
  <div class="col-md-12 animated fadeIn ">
   <div class="panel bg-danger-600">
     <div class="panel-body">
       <div style="text-align: center;font-size:16px;">
        No Attributes to display
       </div>
      </div>
    </div>
  </div>
  {% endif %}
{% include "dashboard/includes/_modal_template.html"  %}
{% endblock %}
{% block custom_js %}
<script type="text/javascript">
  $(document).ready(function() {

  // update modal content from ajax results
  $( ".modal-trigger-ajax").on('click',function() {
    var url = $(this).data('href')
    var prompt_text = $(this).data('title');
    var modal = $(this).attr('href');
    var csrf_token = $(this).data('csrf_token')

    $('.modal-title').html(prompt_text);
    $(".results" ).empty().append('<span class="text-center" style="padding:23px">Loading...<i class=" icon-spinner"></i></span>');
    $(modal).modal();
      var posting = $.get( url, {'csrfmiddlewaretoken':csrf_token });
      // Put the results in a div
      posting.done(function( data ) {
      $(".results" ).empty().append( data );

      });

   });

    var maxHeight = 0;
    $(".equalize").each(function() {
        if ($(this).height() > maxHeight) {
            maxHeight = $(this).height();
        }
    });
    $(".equalize").height(maxHeight);
});

</script>
{% endblock %}

templates/dashboard/product/attributes/modal_confirm_delete.html
{% load i18n %}

<form action="{% url 'dashboard:product-attribute-delete' pk=attribute.pk %}" method="post" novalidate>
  {% csrf_token %}
  <div class="modal-body text-center">

    <h5>
      {% trans "Are you sure?" context "Dashboard confirmation modal" %}
    </h5>
    <p>
      {% blocktrans trimmed context "Modal delete attribute text" %}
        You are about to delete an attribute <strong>{{ attribute }}</strong>.
      {% endblocktrans %}
    </p>
  </div>
  <div class="modal-footer">
    <div class="col-md-6 col-md-offset-3">
      <button type="submit" class="btn btn-danger pull-right">
        {% trans "Delete" context "Dashboard delete action" %}
      </button>
      <a href="#!" data-dismiss="modal" class="pull-left btn modal-action modal-close btn-default">
        {% trans "Cancel" context "Dashboard cancel action" %}
      </a>
    </div>
  </div>
</form>

templates/dashboard/product/attributes/select.html
{% load prices_i18n %}
{% load i18n %}
{% load bootstrap3 %}
{% load materializecss %}
{% load staticfiles %}
{% load attributes %}


{{ form.product_attributes }}
<!--<script type="text/javascript" src="{% static 'backend/js/plugins/forms/styling/uniform.min.js' %}"></script>-->
<!--<script type="text/javascript" src="{% static 'backend/js/plugins/forms/selects/bootstrap_multiselect.js' %}"></script>-->
  <!--<script type="text/javascript" src="{% static 'backend/js/pages/form_multiselect.js' %}"></script>-->
<script>
   /*$('#id_product_attributes').multiselect({
        onChange: function() {
            $.uniform.update();
        }
    });*/
</script>