saleor/cart/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update/(?P<variant_id>\d+)/$', views.update, name='update-line'),
    url(r'^summary/$', views.summary, name='cart-summary'),
    url(r'^shipingoptions/$', views.get_shipping_options,
        name='shipping-options')
]

saleor/dashboard/search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.search, name='search')
]

saleor/dashboard/users/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required

from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
        url(r'^$', permission_required('userprofile.view_user', login_url='not_found')
                (views.users), name='users'),
        url(r'^add/$', permission_required('userprofile.add_user', login_url='not_found')
                (views.user_add), name='user-add'),
        url(r'^users_pdf/$', views.users_pdf, name='users_pdf'),
        url(r'^users_export_csv/$', views.users_export_csv, name='users_export_csv'),
        url(r'^user_process/$',  permission_required('userprofile.add_user')
        (views.user_process), name='user_process'),
        url(r'^detail/(?P<pk>[0-9]+)/$', permission_required('userprofile.change_user', login_url='not_found')(views.user_detail), name='user-detail'),
        url(r'user_trail/$', permission_required('unused.view_trail', login_url='not_found')
                (views.user_trails), name='user_trail'),
        url(r'^usertrail_paginate/', views.usertrail_paginate, name='usertrail_paginate'),
        url( r'^usertrail_search/$', views.usertrail_search, name = 'usertrail_search' ),
        url(r'^delete/(?P<pk>[0-9]+)/$', permission_required('userprofile.delete_user')
                (views.user_delete), name='user-delete'),
    
        url(r'^edit/(?P<pk>[0-9]+)/$', permission_required('userprofile.change_user', login_url='not_found')(views.user_edit), name='user-edit'),
        url(r'^user_update(?P<pk>[0-9]+)/$', permission_required('userprofile.change_user', login_url='not_found')
                (views.user_update), name='user-update'),
        url(r'^user_assign_permission/$', views.user_assign_permission, name='user_assign_permission'),
        url(r'^user_paginate/', views.user_paginate, name='user_paginate'),
        url( r'^users_search/$', views.user_search, name = 'user_search' ),
        
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/search/urls.py
from __future__ import unicode_literals

from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.search, name='search')
]

saleor/urls.py
from rest_framework_jwt.views import obtain_jwt_token
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView
import notifications.urls

from .accounts.urls import urlpatterns as accounts_urls
from .api.cash.urls import urlpatterns as api_cash_urls
from .api.payment.urls import urlpatterns as api_payment_urls
from .api.product.urls import urlpatterns as api_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls

from .order.urls import urlpatterns as order_urls
from .payment.urls import urlpatterns as payment_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

from .api.product import views as api_views
from . import decorators


urlpatterns = [    
	url(r'^', include(core_urls)),    
	url(r'^account/', include(registration_urls)),
	url(r'^accounts/', include(accounts_urls, namespace='accounts')),
	url(r'^api/cash/', include(api_cash_urls, namespace='cash-api')),
	url(r'^api/products/', include(api_urls, namespace='product-api')),
	url(r'^api/payment/', include(api_payment_urls, namespace='payment-api')),
	url(r'^cart/', include(cart_urls, namespace='cart')),
	url(r'^checkout/', include(checkout_urls, namespace='checkout')),
	url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
	url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
	 url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
	url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
	url(r'^order/', include(order_urls, namespace='order')),
	url(r'^payment/$', include(payment_urls, namespace='payment')),
	url(r'^products/', include(product_urls, namespace='product')),
	url(r'^profile/', include(userprofile_urls, namespace='profile')),
	url(r'^search/', include(search_urls, namespace='search')),
	url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
	url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
		name='django.contrib.sitemaps.views.sitemap'),
	url(r'', include('payments.urls')),
	url('', include('social_django.urls', namespace='social')),
	#jwt post token code url
	url(r'^api/auth/token/', obtain_jwt_token),

]

if settings.DEBUG:
	# static files (images, css, javascript, etc.)
	urlpatterns += [
		url(r'^static/(?P<path>.*)$', serve)
	] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/dashboard/search/forms.py
from ...search.backends import get_search_backend
from ...search.forms import SearchForm


class DashboardSearchForm(SearchForm):

    def search(self, queryset_map=None):
        backend = get_search_backend('dashboard')
        query = self.cleaned_data['q']
        results = backend.search(query, queryset_map=queryset_map)
        return results

saleor/search/forms.py
from django import forms
from django.utils.translation import pgettext

from .backends import get_search_backend


class SearchForm(forms.Form):
    q = forms.CharField(label=pgettext('Search form label', 'Query'), required=True)

    def search(self, model_or_queryset):
        backend = get_search_backend('default')
        query = self.cleaned_data['q']
        results = backend.search(query, model_or_queryset=model_or_queryset)
        return results

saleor/dashboard/search/views.py
from django.contrib.admin.views.decorators import staff_member_required
from django.conf import settings
from django.shortcuts import render

from ...order.models import Order
from ...product.models import Product
from ...search.views import paginate_results
from ...userprofile.models import User
from .forms import DashboardSearchForm


@staff_member_required
def search(request):
    form = DashboardSearchForm(data=request.GET or None)
    query = ''
    queryset_map = {
        Product: Product.objects.prefetch_related('images'),
        Order: Order.objects.prefetch_related('user'),
        User: User.objects.all()}
    if form.is_valid():
        results = form.search(queryset_map=queryset_map)
        page = paginate_results(results, request.GET, settings.PAGINATE_BY)
        query = form.cleaned_data['q']
    else:
        page = []
    ctx = {
        'form': form,
        'query': query,
        'results': page,
        'query_string': '?q=%s' % query}
    return render(request, 'dashboard/search/results.html', ctx)

saleor/search/views.py
from __future__ import unicode_literals

from django.core.paginator import Paginator, InvalidPage
from django.conf import settings
from django.http import Http404
from django.shortcuts import render
from .forms import SearchForm
from ..product.utils import products_with_details, products_with_availability


def paginate_results(results, get_data, paginate_by=25):
    paginator = Paginator(results, paginate_by)
    page_number = get_data.get('page', 1)
    try:
        page = paginator.page(page_number)
    except InvalidPage:
        raise Http404('No such page!')
    return page


def search(request):
    form = SearchForm(data=request.GET or None)
    if form.is_valid():
        visible_products = products_with_details(request.user)
        results = form.search(model_or_queryset=visible_products)
        results = products_with_availability(
            results, discounts=request.discounts,
            local_currency=request.currency)
        results = list(results)
        query = form.cleaned_data.get('q', '')
    else:
        results = []
        query = ''
    page = paginate_results(results, request.GET, settings.PAGINATE_BY)
    ctx = {
        'query': query,
        'results': page,
        'query_string': '?q=%s' % query}
    return render(request, 'search/results.html', ctx)

templates/dashboard/product/attributes/pagination/p2.html
{% load staticfiles %}
{% load i18n %}
{% load prices_i18n %}
   <style type="text/css">
     .clickable-row td.td{
      cursor: pointer;
     }
     tr.nb td{border:0px;}
     .nb{border:0px;}
     .table{border:1px solid #ccc}
   </style>
{% if attributes %}
      <div class="panel panel-flat">
        <div class="table-responsives">
         
            <div class="panel-body">
              <table class="table table-striped table-hover datatable-header-footer" style="border-bottom:1px solid #ddd;">
                     <thead>
                      <tr class="bg-primary">
                         <th>#</th>
                        <th>Name</th>
                        <th>Value</th>
                        <th class="text-center">Actions</th>
                      </tr>
                    </thead>
                    <tbody id="p-tb">
                       {% for pk, name, values in attributes %}
                  <tr>
                    <td>{{ pk }}</td>
                    <!-- names -->
                    <td>{{ name }}</td>
                    <!-- values -->
                    <td>
                    {% if values %}
                      {% for value in values %}
                          {{ value }}
                          {% if not forloop.last %}, {% endif %}
                      {% endfor %}
                    {% else %}
                        None
                    {% endif %}
                    </td>
                      <td class="text-center">
                              <!-- Single button -->
                            <div class="btn-group">
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Action <span class="caret"></span>
                              </button>
                              <ul class="dropdown-menu edit-dropdown">
                             {% if perms.product.change_product %}
                                <li><a href="{% url 'dashboard:product-attribute-update' pk=pk %}"><i class="icon-pencil7"></i> EDIT</a></li>
                             {% endif %}
                             {% if perms.product.delete_product %}
                                  <li>
                                     <a href="#modal_instance" data-title='Remove attribute {{ name }}' data-href="{% url 'dashboard:product-attribute-delete' pk=pk %}" class="modal-trigger-ajax"><i class="icon-trash position-left"></i>
                                       REMOVE
                                      </a>
                                   </li>
                             {% endif %}
                              </ul>
                            </div>

                          </td>
                  </tr>
                {% endfor %}
                    </tbody>
               </table>
            </div>
        </div>
         <div class="my-paginate">
            <div id="bootpag-callback" class="text-center bootpag-callback p2-pag" style="padding:20px;">
              <ul class="pagination bootpag pagination-flat pagination-sm"></ul>
              <div class="pull-right pages-nav2">Page 1 of {{pn}}</div>
            </div>
          </div>
      </div>
     {% else %}
  <div class="col-md-12 animated fadeIn ">
   <div class="panel bg-danger-600">
     <div class="panel-body">
       <div style="text-align: center;font-size:16px;">
        No attributes available
       </div>
      </div>
    </div>
  </div>
{% endif %}
    <!-- Core Scripts - Include with every page -->
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
      <script type="text/javascript" src="{% static 'backend/js/plugins/pagination/bootpag.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'backend/js/plugins/pagination/bs_pagination.min.js' %}"></script>
 <script type="text/javascript">
   $(document).ready(function(){
        $('.p2-pag').bootpag({
            total: parseInt('{{pn}}'),
            maxVisible: 3,
            leaps: false
            }).on("page", function(event, num){
                $(".pages-nav2").html("Page " + num +" of "+'{{pn}}'); 
                var gid = '{{gid}}';
                if(gid == 0){
                    $.get("{% url 'dashboard:attr_paginate' %}",{page:num, psize:'{{sz}}'},function(data){
                      $('#p-tb').html(data);
                    });
                }else{
                    $.get("{% url 'dashboard:attr_paginate' %}",{page:num, psize:'{{sz}}',gid:'{{gid}}'},function(data){
                   $('#p-tb').html(data);
                });
                }

        }).children('.pagination').addClass('pagination-flat pagination-sm')

   });
 </script>

templates/dashboard/product/attributes/pagination/paginate.html
{% load staticfiles %}
{% load i18n %}
{% load prices_i18n %}
{% for pk, name, values in attributes %}
  <tr>
    <td>{{ pk }}</td>
    <!-- names -->
    <td>{{ name }}</td>
    <!-- values -->
    <td>
    {% if values %}
      {% for value in values %}
          {{ value }}
          {% if not forloop.last %}, {% endif %}
      {% endfor %}
    {% else %}
        None
    {% endif %}
    </td>
      <td class="text-center">
              <!-- Single button -->
            <div class="btn-group">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Action <span class="caret"></span>
              </button>
              <ul class="dropdown-menu edit-dropdown">
             {% if perms.product.change_product %}
                <li><a href="{% url 'dashboard:product-attribute-update' pk=pk %}"><i class="icon-pencil7"></i> EDIT</a></li>
             {% endif %}
             {% if perms.product.delete_product %}
                  <li>
                     <a href="#modal_instance" data-title='Remove attribute {{ name }}' data-href="{% url 'dashboard:product-attribute-delete' pk=pk %}" class="modal-trigger-ajax"><i class="icon-trash position-left"></i>
                       REMOVE
                      </a>
                   </li>
             {% endif %}
              </ul>
            </div>

          </td>
  </tr>
{% endfor %}
                 


<script type="text/javascript">
 $(document).ready(function(){


 });
</script>

templates/dashboard/product/attributes/pagination/search.html
{% load staticfiles %}
{% load i18n %}
{% load prices_i18n %}
   <style type="text/css">
     .clickable-row td.td{
      cursor: pointer;
     }
     tr.nb td{border:0px;}
     .nb{border:0px;}
     .table{border:1px solid #ccc}
   </style>
{% if attributes %}
      <div class="panel panel-flat">
        <div class="table-responsives">
         
            <div class="panel-body">
              <table class="table table-striped table-hover datatable-header-footer" style="border-bottom:1px solid #ddd;">
                     <thead>
                      <tr class="bg-primary">
                        <th>#</th>
                        <th>Name</th>
                        <th>Value</th>
                        <th class="text-center">Actions</th>
                      </tr>
                    </thead>
                    <tbody id="p-tb">
                    {% for pk, name, values in attributes %}
                  <tr>
                    <td>{{ pk }}</td>
                    <!-- names -->
                    <td>{{ name }}</td>
                    <!-- values -->
                    <td>
                    {% if values %}
                      {% for value in values %}
                          {{ value }}
                          {% if not forloop.last %}, {% endif %}
                      {% endfor %}
                    {% else %}
                        None
                    {% endif %}
                    </td>
                      <td class="text-center">
                              <!-- Single button -->
                            <div class="btn-group">
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Action <span class="caret"></span>
                              </button>
                              <ul class="dropdown-menu edit-dropdown">
                             {% if perms.product.change_product %}
                                <li><a href="{% url 'dashboard:product-attribute-update' pk=pk %}"><i class="icon-pencil7"></i> EDIT</a></li>
                             {% endif %}
                             {% if perms.product.delete_product %}
                                  <li>
                                     <a href="#modal_instance" data-title='Remove attribute {{ name }}' data-href="{% url 'dashboard:product-attribute-delete' pk=pk %}" class="modal-trigger-ajax"><i class="icon-trash position-left"></i>
                                       REMOVE
                                      </a>
                                   </li>
                             {% endif %}
                              </ul>
                            </div>

                          </td>
                  </tr>
                {% endfor %}
                    </tbody>
               </table>
            </div>
        </div>
         <div class="my-paginate">
            <div id="bootpag-callback" class="text-center bootpag-callback p2-pag" style="padding:20px;">
              <ul class="pagination bootpag pagination-flat pagination-sm"></ul>
              <div class="pull-right pages-nav2">Page 1 of {{pn}}</div>
            </div>
          </div>
      </div>
     {% else %}
  <div class="col-md-12 animated fadeIn ">
   <div class="panel bg-danger-600">
     <div class="panel-body">
       <div style="text-align: center;font-size:16px;">
        No attributes available
       </div>
      </div>
    </div>
  </div>
{% endif %}
    <!-- Core Scripts - Include with every page -->
    <script type="text/javascript" src="{% url 'javascript-catalog' %}"></script>
      <script type="text/javascript" src="{% static 'backend/js/plugins/pagination/bootpag.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'backend/js/plugins/pagination/bs_pagination.min.js' %}"></script>
 <script type="text/javascript">
   $(document).ready(function(){
        $('.p2-pag').bootpag({
            total: parseInt('{{pn}}'),
            maxVisible: 3,
            leaps: false
            }).on("page", function(event, num){
                $(".pages-nav2").html("Page " + num +" of "+'{{pn}}'); 

                $.get("{% url 'dashboard:search-attribute' %}",{page:num, psize:'{{sz}}', q:'{{q}}'},function(data){
                   $('#p-tb').html(data);
                });
        }).children('.pagination').addClass('pagination-flat pagination-sm')

   });
 </script>

templates/dashboard/product/attributes/pagination/view.html
{% extends "dashboard/base.html" %}
{% load staticfiles %}
{% load product_first_image from product_images %}
{% load i18n %}
{% load prices_i18n %}

{% block title %}
  Products Attributes
{% endblock %}

 {% block breadcrumbs %}
     <li><a href="{% url 'dashboard:index' %}">Dashboard</a></li>
     <li class="active"><a href="{% url 'dashboard:product-attributes' %}">Products Attributes</a></li>
 {% endblock %}

{% block menu_attributes_class %}active{% endblock %}
 {% block custom_css %}
   <style type="text/css">
     .clickable-row td.td{
      cursor: pointer;
     }
     tr.nb td{border:0px;}
     .nb{border:0px;}
     .table{border:1px solid #ccc}
     .edit-dropdown{
         min-width:150px;
         padding-top:0px;
         padding-bottom:0px;
     }
   </style>
 {% endblock %}

{% block content %}
 <div class="row animated fadeIn">
   <div class="col-md-12">
      <div class="panel panel-flat">
      <div class="panel-heading">
        <h6 class="panel-title">Attributes</h6>
        <div class="heading-elements">
          <ul class="icons-list">
            <li><a data-action="collapse"></a></li>
            <li><a data-action="reload"></a></li>
            <li><a data-action="close"></a></li>
          </ul>
        </div>
      <a class="heading-elements-toggle"><i class="icon-more"></i></a></div>
        <div class="panel-body">
            <div class="col-md-4">
             <label>Search Attributes</label>
              <div class="form-group form-group-material has-feedback">
                <input class="form-control search_user" placeholder="Search" type="text">
                <div class="form-control-feedback">
                  <i class="icon-search4 text-size-base"></i>
                </div>
              </div>
            </div>
            <div class="col-md-2">
              <label>display list size</label>
              <div class="form-group">
                 <select class="bootstrap-select list-sz" style="display: none;" data-width="100%" tabindex="-98">
                    <option value="0" selected>No:</option>
                    <option value="5">5</option>
                    <option value="10">10</option>
                    <option value="20">20</option>
                  </select>
              </div>
            </div>
            <div class="col-md-2">
              <label style="visibility: hidden;"> add</label>
              <div class="form-group">
                {% if perms.product.add_productattribute %}
                 <a class="btn btn-primary text-white btn-xs waves-effect waves-light teal modal-trigger" href="{% url 'dashboard:product-attribute-add' %}" title="{% trans 'Add attribute' context 'Product Attribute add button text' %}">
                  Add Attribute
                </a>
                {% endif %}
              </div>
            </div>
        </div>
      </div>
   </div>
  {% if attributes %}
  <div class="col-md-12">
   <div id="pagination-div">
      <!-- Header and footer fixed -->
      <div class="panel panel-flat">
        <div class="panel-body">
        <div class="table-responsives">
            <table class="table table-striped table-hover datatable-header-footer" style="border-bottom:1px solid #ddd;">
                <thead>
                  <tr class="bg-primary">
                    <th>#</th>
                    <th>Name</th>
                    <th>Value</th>
                    <th class="text-center">Actions</th>
                  </tr>
                </thead>
                <tbody id="tb">
                {% for pk, name, values in attributes %}
                  <tr>
                    <td>{{ pk }}</td>
                    <!-- names -->
                    <td>{{ name }}</td>
                    <!-- values -->
                    <td>
                    {% if values %}
                      {% for value in values %}
                          {{ value }}
                          {% if not forloop.last %}, {% endif %}
                      {% endfor %}
                    {% else %}
                        None
                    {% endif %}
                    </td>
                      <td class="text-center">
                              <!-- Single button -->
                            <div class="btn-group">
                              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Action <span class="caret"></span>
                              </button>
                              <ul class="dropdown-menu edit-dropdown">
                             {% if perms.product.change_product %}
                                <li><a href="{% url 'dashboard:product-attribute-update' pk=pk %}"><i class="icon-pencil7"></i> EDIT</a></li>
                             {% endif %}
                             {% if perms.product.delete_product %}
                                  <li>
                                     <a href="#modal_instance" data-title='Remove attribute {{ name }}' data-href="{% url 'dashboard:product-attribute-delete' pk=pk %}" class="modal-trigger-ajax"><i class="icon-trash position-left"></i>
                                       REMOVE
                                      </a>
                                   </li>
                             {% endif %}
                              </ul>
                            </div>

                          </td>
                  </tr>
                {% endfor %}
                </tbody>
           </table>

        </div>
        </div>
         <div class="my-paginate">
            <div class="text-center bootpag-callback" style="padding:20px;">
              <ul class="pagination bootpag pagination-flat pagination-sm"></ul>
              <div class="pull-right pages-nav">Page 1 of {{totalp}}</div>
            </div>
            <input type="hidden" id="page_size" val="">
          </div>
      </div>
    </div><!-- pagination -->
  </div>
     {% else %}
  <div class="col-md-12 animated fadeIn ">
   <div class="panel bg-danger-600">
     <div class="panel-body">
       <div style="text-align: center;font-size:16px;">
        No attributes available
       </div>
      </div>
    </div>
  </div>
{% endif %}
</div>

{% include "dashboard/includes/_modal_template.html"  %}
{% endblock%}
{% block custom_js %}
  <script type="text/javascript" src="{% static 'backend/js/plugins/forms/selects/bootstrap_multiselect.js' %}"></script>
  <script type="text/javascript" src="{% static 'backend/js/pages/form_multiselect.js' %}"></script>
<script type="text/javascript" src="{% static 'backend/js/plugins/forms/selects/bootstrap_select.min.js' %}"></script>
<script type="text/javascript">
$(document).ready(function() {

// update modal content from ajax results
  $( ".modal-trigger-ajax").on('click',function() {
    var url = $(this).data('href')
    var prompt_text = $(this).data('title');
    var modal = $(this).attr('href');
    var csrf_token = $(this).data('csrf_token')

    $('.modal-title').html(prompt_text);
    $(".results" ).empty().append('<span class="text-center" style="padding:23px">Loading...<i class=" icon-spinner"></i></span>');
    $(modal).modal();
      var posting = $.get( url, {'csrfmiddlewaretoken':csrf_token });
      // Put the results in a div
      posting.done(function( data ) {
      $(".results" ).empty().append( data );

      });

   });

  //** view product modal
  $( "body").on('click', '.modal-trigger-ajax', function() {

    var url = $(this).data('href')
    var prompt_text = $(this).data('title');
    var modal = $(this).attr('href');
    var csrf_token = $(this).data('csrf_token')
    $('.modal-title').html(prompt_text);
    $(".results" ).empty().append('<span class="text-center" style="padding:23px">Loading...<i class=" icon-spinner"></i></span>');
    $(modal).modal();
      var posting = $.get( url, {'csrfmiddlewaretoken':csrf_token });
      // Put the results in a div
      posting.done(function( data ) {
      $(".results" ).empty().append( data );

      });

   });


    $('.export-sz').selectpicker({
          iconBase: 'fa',
          tickIcon: 'fa-dot-circle-o',
          pdfIcon:'fa-file-pdf-o',
          excelIcon:'fa-file-excel-o'
    }).on('change', function(){

        var ts = $(this).val();
        if(ts == 'pdf'){
          var url = "{% url 'dashboard:users_pdf' %}";
          window.open(url, '_blank');

        }else if(ts=='excel'){
          window.location="{% url 'dashboard:users_export_csv' %}";

        }else{
          $(this).val('')
        }
    });

    //**@ display size select
    $('.list-sz').selectpicker().on('change', function(){
        var ts = $(this).val();
        if(ts != '0'){
            $.ajax({ url: "{% url 'dashboard:attr_paginate' %}",type: 'GET',data: {page:1, size:ts}, async:false,success: function(data){
                  $('#pagination-div').html(data);
            }});
        }

     });

    $('.bootpag-callback').bootpag({
        total: parseInt({{totalp}}),
        maxVisible: 3,
        leaps: false
        }).on("page", function(event, num){
            $(".pages-nav").html("Page " + num +" of "+{{totalp}}); // or some ajax content loading...
            $.get("{% url 'dashboard:attr_paginate' %}",{page:num},function(data){
               $('#tb').html(data);
            });
    }).children('.pagination').addClass('pagination-flat pagination-sm')

      var delay = (function(){
        var timer = 0;
        return function(callback, ms){
          clearTimeout (timer);
          timer = setTimeout(callback, ms);
        };
      })();

      $('.search_user').keyup(function() {
        var search_text = $(this).val();
        delay(function(){
           var url = "{% url 'dashboard:search-attribute' %}";
           $.ajax({ url:url, type: 'GET',data: {page:1, q:search_text, },success: function(data){
                  $('#pagination-div').html(data);
           }});
        }, 500 );

      });

  });


</script>
{% endblock %}