saleor/api/product/urls.py
from django.conf.urls import url

from .views import (
    CreateStockAPIView,
    CustomerListAPIView,
    CustomerDetailAPIView,
    ProductListAPIView,
    ProductStockListAPIView,
    SearchSkuListAPIView,
    SalesListAPIView,
    SalesCreateAPIView,
    SalesDetailAPIView,
    SalesDeleteAPIView,
    )


urlpatterns = [
    url(r'^$', ProductListAPIView.as_view(), name='product-list'),
    url(r'^stock$', ProductStockListAPIView.as_view(), name='productstock-list'),
    url(r'^stock/(?P<stock_pk>[0-9]+)$', CreateStockAPIView.as_view(), name='create-stock'),
    url(r'^search-sku/$', SearchSkuListAPIView.as_view(), name='search-sku'),
    url(r'^customer/list/$', CustomerListAPIView.as_view(), name='customer-list'),
    url(r'^customer/list/$', CustomerListAPIView.as_view(), name='customer-list'),
    url(r'^customer-details/(?P<pk>[0-9]+)/$', CustomerDetailAPIView.as_view(), name='costomer-detail'),
    url(r'^list-orders/$', SalesListAPIView.as_view(), name='list-orders'),
    url(r'^create-order/$', SalesCreateAPIView.as_view(), name='create-order'),
    url(r'^sales-details/(?P<pk>[0-9]+)/$', SalesDetailAPIView.as_view(), name='sales-details'),
    url(r'^sales-delete/(?P<pk>[0-9]+)/$', SalesDeleteAPIView.as_view(), name='sales-delete'),

]

saleor/dashboard/product/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, permission_required
from . import api
from . import views, products


urlpatterns = [
    # url(r'^$',permission_required('product.view_product', login_url='not_found')
    # (views.product_list), name='product-list'),

    url(r'^$',permission_required('product.view_product', login_url='not_found')
    (products.view), name='product-list'),
    url(r'^list-paginate/$', products.paginate, name='product-list-paginate'),
    url(r'^list/search/$', products.search, name='product-list-search'),
    url(r'^(?P<pk>[0-9]+)/update/$', permission_required('product.change_product', login_url='not_found')
        (views.product_edit), name='product-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', permission_required('product.delete_product', login_url='not_found')
        (views.product_delete), name='product-delete'),
    url(r'^add/(?P<class_pk>[0-9]+)/$', permission_required('product.add_product', login_url='not_found')
        (views.product_create), name='product-add'),
    url(r'^add/$', permission_required('product.add_product', login_url='not_found')
    (views.product_create), name='product-add'),
    url(r'^fetch_variants/$', permission_required('product.view_product', login_url='not_found')
        (views.fetch_variants), name='fetch-variants'),
    # tax routes
    url(r'^tax/$', permission_required('product.view_producttax', login_url='not_found')
        (views.tax_list), name='tax-list'),
    url(r'^tax/add$', permission_required('product.add_producttax', login_url='not_found')
        (views.tax_add), name='tax-add'),
    url(r'^tax/add/ajax$',
        views.tax_add_ajax, name='tax-add-ajax'),    
    url(r'^tax/delete/(?P<pk>[0-9]+)/$', permission_required('product.delete_producttax', login_url='not_found')
        (views.tax_delete), name='tax-delete'),
    url(r'^tax/edit(?P<pk>[0-9]+)/$', permission_required('product.change_producttax', login_url='not_found')
        (views.tax_edit), name='tax-update'),
    # end tax
    # purchase routes
    url(r'^purchase/$', permission_required('product.view_stock', login_url='not_found')
        (views.stocks), name='purchase-list'),
    # end purchase routes
    # search routes
    url(r'^search_ajax/$',
        views.search_product, name='search-product'),
    url(r'^search_sku/$',
        views.search_sku, name='search-sku'),
    url(r'^search_productclass/$',
        views.search_productclass, name='search-type'),
    # pagination
    url(r'^stocks/$', permission_required('product.view_stock', login_url='not_found')
        (views.stocks), name='stocks'),
    url(r'^stock_paginate/$', views.stock_paginate, name='stock_paginate'),
    url(r'^stock_pages/$', permission_required('product.view_stock', login_url='not_found')
    (views.stock_pages), name='stock_pages'),
    url( r'^stock_search/$', views.stock_search, name = 'stock_search' ),
    url(r'^stock_filter/$',
        views.stock_filter, name='stock_filter'),
     
     url(r'^product_pages/$',
        views.stock_pages, name='product_pages'),
     url(r'^product_filter/$',
        views.product_filter, name='product_filter'),
    # end search routes
    # url(r'^classes/$', permission_required('product.view_productclass', login_url='not_found')
    #     (views.product_class_list), name='product-class-list'),
    url(r'^classes/$', permission_required('product.view_productclass', login_url='not_found')
            (views.class_list_view), name='product-class-list'),
    url(r'^classes/paginate/$', permission_required('product.view_productclass', login_url='not_found')
            (views.paginate_class_list), name='paginate-class-list'),
    url(r'^classes/search/$', permission_required('product.view_productclass', login_url='not_found')
            (views.search_class_list), name='search-class-list'),
    url(r'^classes/add/$', permission_required('product.add_productclass', login_url='not_found')
        (views.product_class_create), name='product-class-add'),
    url(r'^classes/refresh/$',
        views.refresh_producttype, name='refresh_producttype'),    
    
    url(r'^classes/add/new_window/(\d+)/$', permission_required('product.add_productclass', login_url='not_found')
        (views.product_class_create), name='product-class-add-new'),
    
    url(r'^classes/(?P<pk>[0-9]+)/update/$', permission_required('product.change_productclass', login_url='not_found')
        (views.product_class_edit), name='product-class-update'),
    url(r'^classes/(?P<pk>[0-9]+)/delete/$', permission_required('product.delete_productclass', login_url='not_found')
        (views.product_class_delete), name='product-class-delete'),

    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/$', permission_required('product.change_productvariants', login_url='not_found')
        (views.variant_edit), name='variant-update'),
    url(r'^(?P<product_pk>[0-9]+)/variants/add/$', permission_required('product.add_productvariants', login_url='not_found')
        (views.variant_edit), name='variant-add'),
    url(r'^(?P<product_pk>[0-9]+)/variants/(?P<variant_pk>[0-9]+)/delete/$', permission_required('product.delete_productvariants', login_url='not_found')
        (views.variant_delete), name='variant-delete'),
    url(r'^(?P<product_pk>[0-9]+)/variants/bulk_delete/', permission_required('product.delete_productvariants', login_url='not_found')
        (views.variants_bulk_delete), name='variant-bulk-delete'),

    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/$', permission_required('product.change_stock', login_url='not_found')
        (views.stock_edit), name='product-stock-update'),
    url(r'^stock/(?P<stock_pk>[0-9]+)/history$', permission_required('product.view_stock', login_url='not_found')
        (views.stock_history), name='stock-history'),
    url(r'^(?P<product_pk>[0-9]+)/stock/add/$', permission_required('product.add_stock', login_url='not_found')
        (views.stock_edit), name='product-stock-add'),
    url(r'^(?P<product_pk>[0-9]+)/stock/(?P<stock_pk>[0-9]+)/delete/$', permission_required('product.delete_stock', login_url='not_found')
        (views.stock_delete), name='product-stock-delete'),
    url(r'^(?P<product_pk>[0-9]+)/stock/bulk_delete/', permission_required('product.delete_stock', login_url='not_found')
        (views.stock_bulk_delete), name='stock-bulk-delete'),
    url(r'^add_stock_ajax/$',
        views.add_stock_ajax,name='add_stock_ajax'),
    url(r'^re_order/$',
        views.re_order,name='re_order'),
    url(r'^re_order/form/(?P<pk>[0-9]+)$',
        views.re_order_form,name='re_order_form'),
    url(r'^re_order/form/item/(?P<pk>[0-9]+)$',
        views.add_reorder_stock,name='reorder_stock'),
    url(r'^re_order/request/$',
        views.request_order,name='request_order'),  
           

    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/$', permission_required('product.change_productimage', login_url='not_found')
        (views.product_image_edit), name='product-image-update'),
    url(r'^(?P<product_pk>[0-9]+)/images/add/$', permission_required('product.add_productimage', login_url='not_found')
        (views.product_image_edit), name='product-image-add'),
    url(r'^(?P<product_pk>[0-9]+)/images/(?P<img_pk>[0-9]+)/delete/$', permission_required('product.delete_productimage', login_url='not_found')
        (views.product_image_delete), name='product-image-delete'),
    url('^(?P<product_pk>[0-9]+)/images/reorder/$', permission_required('product.change_productimage', login_url='not_found')
        (api.reorder_product_images), name='product-images-reorder'),
    url('^(?P<product_pk>[0-9]+)/images/upload/$', permission_required('product.add_productimage', login_url='not_found')
        (api.upload_image), name='product-images-upload'),

    # url(r'attributes/$', permission_required('product.view_productattribute', login_url='not_found')
    #     (views.attribute_list), name='product-attributes'),
    url(r'attributes/$', permission_required('product.view_productattribute', login_url='not_found')
        (views.view_attr), name='product-attributes'),
    url(r'attributes/paginate/$', permission_required('product.view_productattribute', login_url='not_found')
        (views.paginate_attr), name='attr_paginate'),
    url(r'attributes/search$',
        views.search_attribute, name='search-attribute'),
    
    url(r'attributes/(?P<pk>[0-9]+)/$', permission_required('product.change_productattribute', login_url='not_found')
        (views.attribute_edit), name='product-attribute-update'),
    url(r'attributes/add/$', permission_required('product.add_productattribute', login_url='not_found')
        (views.attribute_edit), name='product-attribute-add'),
    url(r'attributes/add/modal/$', permission_required('product.add_productattribute', login_url='not_found')
    (views.attribute_add_modal), name='product-attribute-add-modal'),
    url(r'attributes/(?P<pk>[0-9]+)/delete/$', permission_required('product.delete_productattribute', login_url='not_found')
        (views.attribute_delete), name='product-attribute-delete'),

    url(r'attributes/ajax_add/$',
        views.attribute_add, name='product-attr-add'),
    url(r'attributes/ajax_add/(\d+)/$',
        views.attribute_add, name='product-attr-add-value'),
    

    url(r'stocklocations/$', permission_required('product.view_stocklocation', login_url='not_found')
        (views.stock_location_list), name='product-stock-location-list'),
    url(r'stocklocations/add/$', permission_required('product.add_stocklocation', login_url='not_found')
        (views.stock_location_edit), name='product-stock-location-add'),
    url(r'stocklocations/(?P<location_pk>[0-9]+)/$', permission_required('product.change_stocklocation', login_url='not_found')
    (views.stock_location_edit), name='product-stock-location-edit'),

saleor/product/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/$',
        views.product_details, name='details'),
    url(r'^category/(?P<path>[a-z0-9-_/]+?)-(?P<category_id>[0-9]+)/$',
        views.category_index, name='category'),
    url(r'(?P<slug>[a-z0-9-]+?)-(?P<product_id>[0-9]+)/add/$',
        views.product_add_to_cart, name="add-to-cart"),
]

saleor/urls.py
from rest_framework_jwt.views import obtain_jwt_token
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve
from django.views.i18n import javascript_catalog
from graphene_django.views import GraphQLView
import notifications.urls

from .accounts.urls import urlpatterns as accounts_urls
from .api.cash.urls import urlpatterns as api_cash_urls
from .api.payment.urls import urlpatterns as api_payment_urls
from .api.product.urls import urlpatterns as api_urls
from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .dashboard.urls import urlpatterns as dashboard_urls
from .data_feeds.urls import urlpatterns as feed_urls

from .order.urls import urlpatterns as order_urls
from .payment.urls import urlpatterns as payment_urls
from .product.urls import urlpatterns as product_urls
from .registration.urls import urlpatterns as registration_urls
from .search.urls import urlpatterns as search_urls
from .userprofile.urls import urlpatterns as userprofile_urls

from .api.product import views as api_views
from . import decorators


urlpatterns = [    
	url(r'^', include(core_urls)),    
	url(r'^account/', include(registration_urls)),
	url(r'^accounts/', include(accounts_urls, namespace='accounts')),
	url(r'^api/cash/', include(api_cash_urls, namespace='cash-api')),
	url(r'^api/products/', include(api_urls, namespace='product-api')),
	url(r'^api/payment/', include(api_payment_urls, namespace='payment-api')),
	url(r'^cart/', include(cart_urls, namespace='cart')),
	url(r'^checkout/', include(checkout_urls, namespace='checkout')),
	url(r'^dashboard/', include(dashboard_urls, namespace='dashboard')),
	url(r'^graphql', GraphQLView.as_view(graphiql=settings.DEBUG)),
	 url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
	url(r'^jsi18n/$', javascript_catalog, name='javascript-catalog'),
	url(r'^order/', include(order_urls, namespace='order')),
	url(r'^payment/$', include(payment_urls, namespace='payment')),
	url(r'^products/', include(product_urls, namespace='product')),
	url(r'^profile/', include(userprofile_urls, namespace='profile')),
	url(r'^search/', include(search_urls, namespace='search')),
	url(r'^feeds/', include(feed_urls, namespace='data_feeds')),
	url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
		name='django.contrib.sitemaps.views.sitemap'),
	url(r'', include('payments.urls')),
	url('', include('social_django.urls', namespace='social')),
	#jwt post token code url
	url(r'^api/auth/token/', obtain_jwt_token),

]

if settings.DEBUG:
	# static files (images, css, javascript, etc.)
	urlpatterns += [
		url(r'^static/(?P<path>.*)$', serve)
	] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

saleor/product/forms.py
from __future__ import unicode_literals

import json

from django import forms
from django.utils.encoding import smart_text
from django.utils.translation import pgettext_lazy
from django_prices.templatetags.prices_i18n import gross

from ..cart.forms import AddToCartForm


class VariantChoiceField(forms.ModelChoiceField):
    discounts = None

    def label_from_instance(self, obj):
        variant_label = smart_text(obj)
        label = pgettext_lazy(
            'Variant choice field label',
            '%(variant_label)s - %(price)s') % {
                'variant_label': variant_label,
                'price': gross(obj.get_price(discounts=self.discounts))}
        return label


class ProductForm(AddToCartForm):
    variant = VariantChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        variant_field = self.fields['variant']
        variant_field.queryset = self.product.variants
        variant_field.discounts = self.cart.discounts
        variant_field.empty_label = None
        images_map = {variant.pk: [vi.image.image.url
                                   for vi in variant.variant_images.all()]
                      for variant in self.product.variants.all()}
        variant_field.widget.attrs['data-images'] = json.dumps(images_map)

    def get_variant(self, cleaned_data):
        return cleaned_data.get('variant')

templates/dashboard/product/stock_locations/form.html
{% extends 'dashboard/base.html' %}

{% load i18n %}
{% load materializecss %}
{% load staticfiles %}

{% block title %}
  {% if location.pk %}
    {{ location }}
  {% else %}
    {% trans "Add new stock location" context "Stock location page title" %}
  {% endif %}
   - {% trans "Stock location" context "Dashboard stock location" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-locations{% endblock %}

{% block header_extra %}
  {% if location.pk %}   
      <li>
        <a class="modal-trigger-ajax" data-title="Remove {{ location.name }}" href="#modal_instance"
        data-href="{% url 'dashboard:product-stock-location-delete' location.pk %}"><i class="icon-trash"></i>
          {% trans "Remove location" context "Stock location detail action" %}
        </a>
      </li>
  
  {% endif %}
{% endblock %}

{% block breadcrumbs %}
  
    <li>
      <a href="{% url 'dashboard:product-stock-location-list' %}" class="breadcrumbs--ellipsed-item">
        {% trans "Stock location" context "Dashboard stock location" %}
      </a>
    </li>
    <li >
      <a href="{% url 'dashboard:sale-list' %}">
        back
      </a>
    </li>
    <li class="active">
      
        {% if location.pk %}
          {{ location }}
        {% else %}
          {% trans "Add new stock location" context "Stock location detail breadcrumbs" %}
        {% endif %}
     
    </li>

{% endblock %}

{% block menu_location_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-6">
      <div class="panel panel-default">
       <div class="panel-body">
        <form method="post" id="form-product" novalidate>
          <div class="card-content card-content-form">
            {% csrf_token %}
            <div class="form-group">
              {{ form.name|materializecss }}
            </div>
          </div>
          <div class="card-action right-align">
            {% if location.pk %}
              <a href="{% url 'dashboard:product-stock-location-list' %}" class="btn btn-flat">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn btn-primary waves-effect waves-light">
                {% trans "Update" context "Dashboard update action" %}
              </button>
            {% else %}
              <a href="{% url 'dashboard:product-stock-location-list' %}" class="btn btn-flat">
                {% trans "Cancel" context "Dashboard cancel action" %}
              </a>
              <button type="submit" class="btn btn-primary waves-effect waves-light">
                {% trans "Create" context "Dashboard create action" %}
              </button>
            {% endif %}
          </div>
        </form>
        </div>
      </div>
    </div>
    <div class="col m12 l3 help-box"></div>
  </div>
{% include "dashboard/includes/_modal_template.html"  %}
{% endblock %}
{% block custom_js %}
<script type="text/javascript" src="{% static 'backend/js/backend.js' %}"></script>
{% endblock %}

templates/dashboard/product/stock_locations/list.html
{% extends 'dashboard/base.html' %}
{% load i18n %}
{% load materializecss %}
{% load staticfiles %}

{% block title %}
  {% trans "Stock locations" context "Dashboard stock location" %} - {{ block.super }}
{% endblock %}

{% block body_class %}body-locations{% endblock %}

{% block header_extra %}
  <li>
    <a class="btn " href="{% url 'dashboard:product-stock-location-add' %}" title="{% trans "Add stock location" context "Stock location list add button text" %}">
      <i class="icon-plus22"></i>Add stock
    </a>
  </li>
{% endblock %}

{% block breadcrumbs %}

    <li class="active">
      {% trans "Stock locations" context "Dashboard stock location" %}
    </li>
  
{% endblock %}

{% block menu_location_class %} active{% endblock %}

{% block content %}
  <div class="row">
    <div class='table-responsive'>
  <table class="table table-striped table-hover fixed_headers">
    <thead>
      <tr class="bg-primary">    
        <th>#</th>    
        <th>Location Name</th>                 
      </tr>
    </thead>    
    <tbody>
    {% if locations %}
    {% for location in locations %}
      <tr class="td" data-href="{% url 'dashboard:product-stock-location-edit' location.pk %}">
        <td>#{{ forloop.counter }}</td>
        <td>{{ location }}</td>
      </tr>
    {% endfor %}
    {% endif %}
    </tbody>
    </table>
  </div>
      
    </div>
 

{% endblock %}
{% block custom_js %}
<style type="text/css">
  .td { cursor: pointer; }
</style>
<script type="text/javascript">
  $('.td').on('click',function(){
     var href = $(this).data('href');
     window.location=href;
  });
</script>
{% endblock %}

templates/dashboard/product/stock_locations/modal_confirm_delete.html
{% load i18n %}

<form action="{% url 'dashboard:product-stock-location-delete' location.pk %}" method="post" novalidate>
  {% csrf_token %}
  <div class="modal-body">
    <h5>
      {% trans "Are you sure?" context "Dashboard confirmation modal" %}
    </h5>
    <div class="row">
      <div class="col l12">
        {% blocktrans trimmed context "Modal delete stock location text" %}
          You are about to delete a stock location <strong>{{ location }}</strong>.
        {% endblocktrans %}
      </div>
    </div>
    {% if stock_count %}
      <p class="text-semibold">
      {% blocktrans trimmed count counter=stock_count context "Modal delete stock location text" %}
        There is one stock associated with this stock location that will be deleted.
        {% plural %}
        There are {{ counter }} stocks associated with this stock location that will be deleted.
        </p>
      {% endblocktrans %}
    {% endif %}
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-">
      {% trans "Delete" context "Dashboard delete action" %}
    </button>
    <a href="#!" data-dismiss="modal" class="btn modal-action modal-close btn-flat">
      {% trans "Cancel" context "Dashboard cancel action" %}
    </a>
  </div>
</form>